// AUTO-GENERATED by scripts/stage-audio.mjs — do not edit by hand.
// SFX are 64 kbps mono AAC; music is the source MP3. Ids on the left are what
// the app plays (see src/lib/audio/).

export interface MusicTrack {
  id: string;
  title: string;
  src: string;
}

/** Effect id → one or more variants (the player picks at random). */
export const SFX_SOURCES: Record<string, string[]> = {
  "ui-click": [
    "/audio/sfx/ui-click.m4a"
  ],
  "ui-open": [
    "/audio/sfx/ui-open.m4a"
  ],
  "ui-click-battle": [
    "/audio/sfx/ui-click-battle.m4a"
  ],
  "attack-swing": [
    "/audio/sfx/attack-swing.m4a"
  ],
  "hit-melee": [
    "/audio/sfx/hit-melee.m4a"
  ],
  "hit-ranged": [
    "/audio/sfx/hit-ranged.m4a"
  ],
  "hurt": [
    "/audio/sfx/hurt.m4a"
  ],
  "hurt-boss": [
    "/audio/sfx/hurt-boss.m4a"
  ],
  "low-health": [
    "/audio/sfx/low-health.m4a"
  ],
  "special": [
    "/audio/sfx/special-1.m4a",
    "/audio/sfx/special-2.m4a"
  ],
  "finisher": [
    "/audio/sfx/finisher-1.m4a",
    "/audio/sfx/finisher-2.m4a"
  ],
  "walk": [
    "/audio/sfx/walk.m4a"
  ],
  "reward-xp": [
    "/audio/sfx/reward-xp.m4a"
  ],
  "reward-ember": [
    "/audio/sfx/reward-ember.m4a"
  ],
  "spend": [
    "/audio/sfx/spend.m4a"
  ]
};

export type SfxId = keyof typeof SFX_SOURCES;

/** Everywhere outside a fight: home, explore, shop, settings, training. */
export const HOME_TRACKS: MusicTrack[] = [
  {
    "id": "home-grace-at-dawnfall",
    "title": "Grace at Dawnfall",
    "src": "/audio/music/home-grace-at-dawnfall.mp3"
  },
  {
    "id": "home-grace-at-dawnfall-2",
    "title": "Grace at Dawnfall II",
    "src": "/audio/music/home-grace-at-dawnfall-2.mp3"
  },
  {
    "id": "home-of-grace",
    "title": "Home of Grace",
    "src": "/audio/music/home-of-grace.mp3"
  },
  {
    "id": "home-of-grace-2",
    "title": "Home of Grace II",
    "src": "/audio/music/home-of-grace-2.mp3"
  }
];

/** Matches, from the first round through the post-match beats. */
export const BATTLE_TRACKS: MusicTrack[] = [
  {
    "id": "battle-everflame-hymn",
    "title": "Everflame Battle Hymn",
    "src": "/audio/music/battle-everflame-hymn.mp3"
  },
  {
    "id": "battle-everflame-hymn-2",
    "title": "Everflame Battle Hymn II",
    "src": "/audio/music/battle-everflame-hymn-2.mp3"
  }
];
