// AUTO-GENERATED by scripts/stage-art.mjs — do not edit by hand.
// Strip metadata measured from the PNG headers at staging time.

export interface EnemyAnimMeta {
  file: string;
  frames: number;
  frameW: number;
  frameH: number;
}

export interface EnemyMeta {
  id: string;
  name: string;
  /** 1 = small (verse L1-2) · 2 = medium (L3-6) · 3 = boss (L7 + campaign bosses) */
  tier: 1 | 2 | 3;
  /** Rendered height in the match scene (art density varies wildly per pack). */
  displayH: number;
  anims: Partial<Record<"idle" | "attack" | "hurt" | "death", EnemyAnimMeta>>;
}

export const ENEMY_META: EnemyMeta[] = [
  {
    "id": "orc",
    "name": "Orc",
    "tier": 1,
    "displayH": 130,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 100,
        "frameH": 100
      },
      "attack": {
        "file": "attack.png",
        "frames": 6,
        "frameW": 100,
        "frameH": 100
      },
      "hurt": {
        "file": "hurt.png",
        "frames": 4,
        "frameW": 100,
        "frameH": 100
      },
      "death": {
        "file": "death.png",
        "frames": 4,
        "frameW": 100,
        "frameH": 100
      }
    }
  },
  {
    "id": "blood-monster",
    "name": "Blood Monster",
    "tier": 1,
    "displayH": 130,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 100,
        "frameH": 100
      },
      "attack": {
        "file": "attack.png",
        "frames": 8,
        "frameW": 100,
        "frameH": 100
      },
      "hurt": {
        "file": "hurt.png",
        "frames": 4,
        "frameW": 100,
        "frameH": 100
      },
      "death": {
        "file": "death.png",
        "frames": 4,
        "frameW": 100,
        "frameH": 100
      }
    }
  },
  {
    "id": "demon-imp",
    "name": "Imp",
    "tier": 1,
    "displayH": 130,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 100,
        "frameH": 100
      },
      "attack": {
        "file": "attack.png",
        "frames": 7,
        "frameW": 100,
        "frameH": 100
      },
      "hurt": {
        "file": "hurt.png",
        "frames": 4,
        "frameW": 100,
        "frameH": 100
      },
      "death": {
        "file": "death.png",
        "frames": 4,
        "frameW": 100,
        "frameH": 100
      }
    }
  },
  {
    "id": "fire-skull",
    "name": "Fire Skull",
    "tier": 1,
    "displayH": 120,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 8,
        "frameW": 96,
        "frameH": 112
      }
    }
  },
  {
    "id": "lizzard",
    "name": "Lizzard",
    "tier": 1,
    "displayH": 74,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 64,
        "frameH": 32
      },
      "attack": {
        "file": "attack.png",
        "frames": 5,
        "frameW": 64,
        "frameH": 32
      },
      "hurt": {
        "file": "hurt.png",
        "frames": 3,
        "frameW": 64,
        "frameH": 32
      }
    }
  },
  {
    "id": "snake",
    "name": "Serpent",
    "tier": 1,
    "displayH": 64,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 20,
        "frameH": 20
      },
      "attack": {
        "file": "attack.png",
        "frames": 4,
        "frameW": 27,
        "frameH": 21
      },
      "hurt": {
        "file": "hurt.png",
        "frames": 3,
        "frameW": 24,
        "frameH": 20
      }
    }
  },
  {
    "id": "crow",
    "name": "Crow",
    "tier": 1,
    "displayH": 92,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 3,
        "frameW": 48,
        "frameH": 48
      },
      "attack": {
        "file": "attack.png",
        "frames": 2,
        "frameW": 48,
        "frameH": 48
      }
    }
  },
  {
    "id": "reaper",
    "name": "Reaper",
    "tier": 1,
    "displayH": 118,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 32,
        "frameH": 48
      },
      "attack": {
        "file": "attack.png",
        "frames": 11,
        "frameW": 32,
        "frameH": 48
      }
    }
  },
  {
    "id": "ghost",
    "name": "Ghost",
    "tier": 1,
    "displayH": 110,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 64,
        "frameH": 64
      }
    }
  },
  {
    "id": "flying-eye",
    "name": "Flying Eye",
    "tier": 1,
    "displayH": 92,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 8,
        "frameW": 48,
        "frameH": 48
      }
    }
  },
  {
    "id": "meerman",
    "name": "Meerman",
    "tier": 1,
    "displayH": 72,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 2,
        "frameW": 27,
        "frameH": 32
      }
    }
  },
  {
    "id": "phantom",
    "name": "Phantom",
    "tier": 2,
    "displayH": 140,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 7,
        "frameW": 64,
        "frameH": 80
      },
      "attack": {
        "file": "attack.png",
        "frames": 4,
        "frameW": 64,
        "frameH": 80
      },
      "death": {
        "file": "death.png",
        "frames": 7,
        "frameW": 64,
        "frameH": 80
      }
    }
  },
  {
    "id": "hell-beast",
    "name": "Hell Beast",
    "tier": 2,
    "displayH": 200,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 80,
        "frameH": 160
      },
      "attack": {
        "file": "attack.png",
        "frames": 4,
        "frameW": 80,
        "frameH": 160
      }
    }
  },
  {
    "id": "hell-hound",
    "name": "Hell Hound",
    "tier": 2,
    "displayH": 105,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 11,
        "frameW": 64,
        "frameH": 48
      },
      "attack": {
        "file": "attack.png",
        "frames": 5,
        "frameW": 64,
        "frameH": 48
      }
    }
  },
  {
    "id": "nightmare",
    "name": "Nightmare",
    "tier": 2,
    "displayH": 150,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 160,
        "frameH": 96
      },
      "attack": {
        "file": "attack.png",
        "frames": 3,
        "frameW": 160,
        "frameH": 96
      }
    }
  },
  {
    "id": "slime",
    "name": "Slime",
    "tier": 2,
    "displayH": 110,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 118,
        "frameH": 79
      }
    }
  },
  {
    "id": "werewolf",
    "name": "Werewolf",
    "tier": 2,
    "displayH": 140,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 5,
        "frameW": 96,
        "frameH": 76
      },
      "attack": {
        "file": "attack.png",
        "frames": 6,
        "frameW": 96,
        "frameH": 76
      }
    }
  },
  {
    "id": "mutant-toad",
    "name": "Mutant Toad",
    "tier": 2,
    "displayH": 128,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 80,
        "frameH": 64
      },
      "attack": {
        "file": "attack.png",
        "frames": 3,
        "frameW": 80,
        "frameH": 64
      }
    }
  },
  {
    "id": "centaur",
    "name": "Centaur",
    "tier": 3,
    "displayH": 200,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 112,
        "frameH": 144
      }
    }
  },
  {
    "id": "dragon",
    "name": "Dragon",
    "tier": 3,
    "displayH": 150,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 144,
        "frameH": 64
      },
      "attack": {
        "file": "attack.png",
        "frames": 7,
        "frameW": 144,
        "frameH": 64
      }
    }
  },
  {
    "id": "ogre",
    "name": "Ogre",
    "tier": 3,
    "displayH": 175,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 144,
        "frameH": 80
      },
      "attack": {
        "file": "attack.png",
        "frames": 7,
        "frameW": 144,
        "frameH": 80
      }
    }
  },
  {
    "id": "treant",
    "name": "Treant",
    "tier": 3,
    "displayH": 175,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 80,
        "frameH": 84
      }
    }
  },
  {
    "id": "vampire",
    "name": "Vampire",
    "tier": 3,
    "displayH": 195,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 4,
        "frameW": 121,
        "frameH": 110
      }
    }
  },
  {
    "id": "wizard",
    "name": "Wizard",
    "tier": 3,
    "displayH": 200,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 95,
        "frameH": 133
      }
    }
  },
  {
    "id": "arch-demon",
    "name": "Arch Demon",
    "tier": 3,
    "displayH": 220,
    "anims": {
      "idle": {
        "file": "idle.png",
        "frames": 6,
        "frameW": 160,
        "frameH": 144
      },
      "attack": {
        "file": "attack.png",
        "frames": 6,
        "frameW": 256,
        "frameH": 176
      }
    }
  }
];
