// AUTO-GENERATED by scripts/stage-art.mjs — do not edit by hand.
// Parallax layers in back → front order, with native pixel sizes.

export interface EnvLayer {
  src: string;
  w: number;
  h: number;
}

export interface EnvMeta {
  id: string;
  layers: EnvLayer[];
}

export const ENVIRONMENTS: EnvMeta[] = [
  {
    "id": "forest-glow",
    "layers": [
      {
        "src": "/environments/forest-glow/1.png",
        "w": 272,
        "h": 160
      },
      {
        "src": "/environments/forest-glow/2.png",
        "w": 272,
        "h": 160
      },
      {
        "src": "/environments/forest-glow/3.png",
        "w": 272,
        "h": 160
      },
      {
        "src": "/environments/forest-glow/4.png",
        "w": 272,
        "h": 160
      }
    ]
  },
  {
    "id": "forest-deep",
    "layers": [
      {
        "src": "/environments/forest-deep/1.png",
        "w": 272,
        "h": 160
      },
      {
        "src": "/environments/forest-deep/2.png",
        "w": 272,
        "h": 160
      },
      {
        "src": "/environments/forest-deep/3.png",
        "w": 272,
        "h": 160
      }
    ]
  },
  {
    "id": "forest-road",
    "layers": [
      {
        "src": "/environments/forest-road/1.png",
        "w": 80,
        "h": 224
      },
      {
        "src": "/environments/forest-road/2.png",
        "w": 112,
        "h": 224
      },
      {
        "src": "/environments/forest-road/3.png",
        "w": 240,
        "h": 224
      }
    ]
  },
  {
    "id": "mist-forest",
    "layers": [
      {
        "src": "/environments/mist-forest/1.png",
        "w": 512,
        "h": 224
      },
      {
        "src": "/environments/mist-forest/2.png",
        "w": 160,
        "h": 224
      },
      {
        "src": "/environments/mist-forest/3.png",
        "w": 336,
        "h": 224
      },
      {
        "src": "/environments/mist-forest/4.png",
        "w": 208,
        "h": 224
      }
    ]
  },
  {
    "id": "rocky-pass",
    "layers": [
      {
        "src": "/environments/rocky-pass/1.png",
        "w": 512,
        "h": 240
      },
      {
        "src": "/environments/rocky-pass/2.png",
        "w": 512,
        "h": 240
      },
      {
        "src": "/environments/rocky-pass/3.png",
        "w": 512,
        "h": 240
      }
    ]
  },
  {
    "id": "junk-wastelands",
    "layers": [
      {
        "src": "/environments/junk-wastelands/1.png",
        "w": 144,
        "h": 240
      },
      {
        "src": "/environments/junk-wastelands/2.png",
        "w": 336,
        "h": 240
      },
      {
        "src": "/environments/junk-wastelands/3.png",
        "w": 512,
        "h": 240
      }
    ]
  },
  {
    "id": "underwater",
    "layers": [
      {
        "src": "/environments/underwater/1.png",
        "w": 256,
        "h": 192
      },
      {
        "src": "/environments/underwater/2.png",
        "w": 256,
        "h": 192
      },
      {
        "src": "/environments/underwater/3.png",
        "w": 512,
        "h": 192
      }
    ]
  },
  {
    "id": "lava",
    "layers": [
      {
        "src": "/environments/lava/1.png",
        "w": 432,
        "h": 240
      },
      {
        "src": "/environments/lava/2.png",
        "w": 196,
        "h": 240
      }
    ]
  },
  {
    "id": "gothic-castle",
    "layers": [
      {
        "src": "/environments/gothic-castle/1.png",
        "w": 480,
        "h": 336
      }
    ]
  }
];
