"use client";

// PIXEL STYLE-GUIDE / ACCEPTANCE SCREEN (Build Brief §0.7).
//
// The regression test for the whole visual system: one stage background, one
// character sprite composited WITH it in the same canvas buffer, a tokened UI
// panel + button, an icon row, and a line of the pixel font — all inside the
// PixelShell at 2×/3×/4×. Acceptance: every art-pixel across all five
// elements renders at exactly the same physical size.
//
// ALL ART HERE IS LABELED PLACEHOLDER (public/pixel-samples/, procedurally
// generated by scripts/gen-placeholder-art.mjs). Final assets are validated
// against this screen via scripts/normalize-art.mjs before they ship.

import { useCallback, useState } from "react";
import { Press_Start_2P } from "next/font/google";
import { PixelShell } from "@/pixel/PixelShell";
import { PixelStage, usePixelImages } from "@/pixel/PixelStage";
import { PIXEL } from "@/pixel/tokens";

const pixelFont = Press_Start_2P({ weight: "400", subsets: ["latin"] });

/* eslint-disable @next/next/no-img-element */

const SAMPLES = [
  "/pixel-samples/stage-bg.png",
  "/pixel-samples/sprite-guard.png",
];

const ICONS = ["sword", "everflame", "great-tree", "scroll"];

export default function StyleGuidePage() {
  const [scale, setScale] = useState<number | "auto">(2);
  const images = usePixelImages(SAMPLES);

  const draw = useCallback(
    (ctx: CanvasRenderingContext2D) => {
      if (!images) return;
      const [bg, guard] = images;
      // background and sprite share one buffer — one pixel density by law
      ctx.drawImage(bg!, 0, 0);
      ctx.drawImage(guard!, 96, 176); // feet on the ground band
    },
    [images],
  );

  return (
    <PixelShell forceScale={scale === "auto" ? undefined : scale}>
      <div className={pixelFont.className} style={{ position: "relative", width: "100%", height: "100%" }}>
        {/* --- the stage: bg + sprite composited in-canvas --- */}
        <PixelStage draw={draw} style={{ position: "absolute", inset: 0 }} />

        {/* --- pixel font line (native 8px × --u) --- */}
        <p
          style={{
            position: "absolute",
            top: "var(--s7)",
            left: 0,
            right: 0,
            textAlign: "center",
            fontSize: "var(--font-px)",
            lineHeight: 2,
            color: "var(--everflame-core)",
            margin: 0,
          }}
        >
          THE SWORD IS LIVING
        </p>

        {/* --- UI panel with button + icon row + scale switcher --- */}
        <div
          style={{
            position: "absolute",
            left: "var(--s4)",
            right: "var(--s4)",
            bottom: "var(--s4)",
            background: "var(--parchment)",
            border: "calc(var(--u) * 1) solid var(--parchment-ink)",
            boxShadow: "calc(var(--u) * 2) calc(var(--u) * 2) 0 var(--darkness-void)",
            padding: "var(--s3)",
          }}
        >
          <p
            style={{
              margin: 0,
              fontSize: "var(--font-px)",
              lineHeight: 1.5,
              color: "var(--parchment-ink)",
            }}
          >
            PLACEHOLDER ART
          </p>
          <p
            style={{
              margin: "var(--s1) 0 var(--s2)",
              fontSize: "var(--font-px)",
              lineHeight: 1.5,
              color: "var(--parchment-ink-soft)",
            }}
          >
            NOT FINAL — GRID TEST
          </p>

          {/* icon row: 16×16 icons + the 24×24 sigil, all at native × --u */}
          <div style={{ display: "flex", alignItems: "flex-end", gap: "var(--s2)", marginBottom: "var(--s2)" }}>
            {ICONS.map((name) => (
              <img
                key={name}
                src={`/pixel-samples/icon-${name}.png`}
                alt={`${name} placeholder icon`}
                data-testid={`icon-${name}`}
                style={{ width: `calc(var(--u) * ${PIXEL.ICON})`, height: `calc(var(--u) * ${PIXEL.ICON})` }}
                draggable={false}
              />
            ))}
            <img
              src="/pixel-samples/icon-hero-sigil.png"
              alt="guard sigil placeholder icon"
              data-testid="icon-sigil"
              style={{ width: `calc(var(--u) * ${PIXEL.ICON_HERO})`, height: `calc(var(--u) * ${PIXEL.ICON_HERO})` }}
              draggable={false}
            />
          </div>

          {/* the button */}
          <button
            style={{
              display: "block",
              width: "100%",
              background: "var(--everflame)",
              border: "calc(var(--u) * 1) solid var(--everflame-deep)",
              boxShadow: "0 calc(var(--u) * 1) 0 var(--everflame-deep)",
              padding: "var(--s2)",
              fontSize: "var(--font-px)",
              fontFamily: "inherit",
              color: "var(--parchment-ink)",
              cursor: "pointer",
            }}
          >
            TAKE YOUR STAND
          </button>

          {/* scale switcher */}
          <div style={{ display: "flex", gap: "var(--s1)", marginTop: "var(--s2)" }}>
            {([2, 3, 4, "auto"] as const).map((s) => (
              <button
                key={s}
                onClick={() => setScale(s)}
                style={{
                  flex: 1,
                  background: scale === s ? "var(--temple-stone-dark)" : "var(--temple-stone-light)",
                  color: scale === s ? "var(--parchment-light)" : "var(--parchment-ink)",
                  border: "calc(var(--u) * 1) solid var(--temple-stone-deep)",
                  padding: "var(--s1)",
                  fontSize: "var(--font-px)",
                  fontFamily: "inherit",
                  cursor: "pointer",
                }}
              >
                {s === "auto" ? "A" : `${s}X`}
              </button>
            ))}
          </div>
        </div>
      </div>
    </PixelShell>
  );
}
