// Build-time: convert the verified local Bible datasets (data/bible/{kjv,asv,web})
// into compact, lazy-loadable assets, with integrity checks against canonical counts.
//
//   public/bible/<tr>.json           → { "GEN.1.1": "In the beginning...", ... } (minified)
//   src/lib/bible/books.generated.ts → 66-book catalog (code/name/testament/chapter→verse counts)
//
// Verse text is NEVER generated or edited here — this script only reshapes the
// verified datasets under data/bible/ (see their READMEs for provenance).
// WEB is picked up automatically once harvested into data/bible/web/.
// Re-run with `npm run gen:bible`.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", ".."); // .../UpWord/Versuz
const bibleDir = resolve(repoRoot, "data", "bible");
const outPublic = resolve(__dirname, "..", "public", "bible");
const outGen = resolve(__dirname, "..", "src", "lib", "bible");

// Canonical integrity expectations (Protestant 66-book canon).
// Per-translation verse totals come from each dataset's verified README;
// KJV includes the Textus Receptus verses that some translations omit.
const CANON = { books: 66, chapters: 1189 };
const EXPECTED_VERSES = { kjv: 31102, asv: 31086, web: null }; // web: fill in when harvested

const TRANSLATIONS = ["kjv", "asv", "web"];

function load(tr) {
  const path = resolve(bibleDir, tr, `${tr}.json`);
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8"));
}

function integrityCheck(tr, rows) {
  const problems = [];
  const ids = new Set();
  const byBook = new Map();
  for (const v of rows) {
    if (!v.text || !v.text.trim()) problems.push(`${v.id}: empty text`);
    if (ids.has(v.id)) problems.push(`${v.id}: duplicate id`);
    ids.add(v.id);
    if (!/^[A-Z0-9]{3}\.\d+\.\d+$/.test(v.id)) problems.push(`${v.id}: malformed USFM id`);
    if (!byBook.has(v.book_code)) byBook.set(v.book_code, new Set());
    byBook.get(v.book_code).add(v.chapter);
  }
  const chapterCount = [...byBook.values()].reduce((n, s) => n + s.size, 0);
  if (byBook.size !== CANON.books)
    problems.push(`book count ${byBook.size} ≠ ${CANON.books}`);
  if (chapterCount !== CANON.chapters)
    problems.push(`chapter count ${chapterCount} ≠ ${CANON.chapters}`);
  const expected = EXPECTED_VERSES[tr];
  if (expected != null && rows.length !== expected)
    problems.push(`verse count ${rows.length} ≠ expected ${expected}`);
  if (problems.length) {
    console.error(`✗ ${tr.toUpperCase()} integrity FAILED:\n  ` + problems.slice(0, 20).join("\n  "));
    process.exit(1);
  }
  console.log(`✓ ${tr.toUpperCase()} integrity: ${byBook.size} books · ${chapterCount} chapters · ${rows.length} verses`);
}

function compact(rows) {
  const map = {};
  for (const v of rows) map[v.id] = v.text;
  return map;
}

mkdirSync(outPublic, { recursive: true });
mkdirSync(outGen, { recursive: true });

const loaded = {};
const available = [];
for (const tr of TRANSLATIONS) {
  const rows = load(tr);
  if (!rows) {
    console.log(`- ${tr.toUpperCase()}: not harvested yet (data/bible/${tr}/ missing) — skipped`);
    continue;
  }
  integrityCheck(tr, rows);
  writeFileSync(resolve(outPublic, `${tr}.json`), JSON.stringify(compact(rows)));
  loaded[tr] = rows;
  available.push(tr.toUpperCase());
}

if (!loaded.kjv) {
  console.error("KJV dataset is required (canonical book/chapter catalog source).");
  process.exit(1);
}

// Book catalog from KJV (canonical 66-book ordering) with verse-per-chapter counts.
const bookCodes = JSON.parse(readFileSync(resolve(bibleDir, "kjv", "book-codes.json"), "utf8"));
const meta = new Map(bookCodes.map((b) => [b.usfm_code, b]));

const byBook = new Map();
const order = [];
for (const v of loaded.kjv) {
  if (!byBook.has(v.book_code)) {
    byBook.set(v.book_code, new Map());
    order.push(v.book_code);
  }
  const chapters = byBook.get(v.book_code);
  chapters.set(v.chapter, Math.max(chapters.get(v.chapter) ?? 0, v.verse));
}

const books = order.map((code) => {
  const chapters = byBook.get(code);
  const chapterNums = [...chapters.keys()].sort((a, b) => a - b);
  const m = meta.get(code);
  return {
    code,
    name: m?.book_name ?? code,
    number: m?.book_number ?? 0,
    testament: m?.testament ?? "OT",
    versesPerChapter: chapterNums.map((c) => chapters.get(c)),
  };
});
books.sort((a, b) => a.number - b.number);

const banner = `// AUTO-GENERATED by scripts/gen-bible.mjs. Do not edit by hand.
// 66-book catalog with verse-per-chapter counts, for reference display, Browse
// navigation, and adjacency checks without loading the full text.
// Available translations at build time: ${available.join(", ")}.
// Re-generate with: npm run gen:bible

export interface BibleBook {
  code: string;
  name: string;
  number: number;
  testament: "OT" | "NT";
  /** versesPerChapter[i] = number of verses in chapter (i + 1). */
  versesPerChapter: number[];
}

export const AVAILABLE_TRANSLATIONS = ${JSON.stringify(available)} as const;

export const BOOKS: BibleBook[] = `;

writeFileSync(
  resolve(outGen, "books.generated.ts"),
  banner + JSON.stringify(books, null, 2) + ";\n",
);
console.log(`Wrote ${available.length} translation map(s) + books.generated.ts (${books.length} books)`);
