// Re-runnable audio stager: the raw pack in ../Audio/ → public/audio/.
//
//  · SFX  — the Helton Yan single-variant WAVs are ~1.8 MB each at pack
//    quality. They ship as 64 kbps mono AAC (.m4a) instead: ~7 KB apiece,
//    which is imperceptible for a 2-second combat sound and keeps the whole
//    effect set around a tenth of a megabyte. Conversion runs through macOS
//    `afconvert` (no ffmpeg on this machine), so the OUTPUT is committed —
//    Vercel never needs the tool.
//  · MUSIC — already 181 kbps MP3. Copied as-is: re-encoding lossy→lossy
//    would cost quality for ~1 MB a track, and only one track streams at a
//    time anyway.
//
// Usage: node scripts/stage-audio.mjs
// Emits: public/audio/{sfx,music}/… + src/config/audio.generated.ts

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const RAW = path.join(ROOT, "..", "Audio");
const OUT_SFX = path.join(ROOT, "public", "audio", "sfx");
const OUT_MUSIC = path.join(ROOT, "public", "audio", "music");

// --- SFX: app id ← the folder Alex labelled in Audio/Misc ------------------
// Where two files share a folder, both ship and the app picks at random.
const SFX = {
  "ui-click": ["interface/click/UIClick_INTERFACE-Strong Click 1_HY_PC-001.wav"],
  "ui-open": ["interface/open menu/UIClick_INTERFACE-Rattling Click_HY_PC-001.wav"],
  // Everything tapped inside a fight EXCEPT Check, which keeps the plain click
  // so the "I'm committing my answer" beat stays distinct.
  "ui-click-battle": ["interface/positive click/UIClick_INTERFACE-Positive Click_HY_PC-001.wav"],
  "attack-swing": ["weapon slash/DSGNMisc_MELEE-Sword Slash_HY_PC-001.wav"],
  "hit-melee": ["give damage/handheld attack/FGHTImpt_MELEE-Swish Hit_HY_PC-001.wav"],
  "hit-ranged": ["give damage/bow attack/DSGNMisc_PROJECTILE-Laser Shot_HY_PC-001.wav"],
  hurt: ["take damage/regular attack/FGHTImpt_MELEE-Gut Punch_HY_PC-001.wav"],
  "hurt-boss": ["take damage/boss attack/DSGNImpt_EXPLOSION-Scorched_HY_PC-001.wav"],
  "low-health": ["1 health/MAGSpel_CAST-Panic Energy_HY_PC-001.wav"],
  special: [
    "fire/DSGNMisc_SKILL RELEASE-Fire Sphere_HY_PC-001.wav",
    "fire/DSGNMisc_SKILL RELEASE-Flame Ball_HY_PC-001.wav",
  ],
  finisher: [
    "finisher/DSGNMisc_SKILL IMPACT-Critical Strike_HY_PC-001.wav",
    "finisher/DSGNMisc_SKILL IMPACT-Crunchy Burst_HY_PC-001.wav",
  ],
  walk: ["walking/FEETMisc_STEP-Boots on Concrete_HY_PC-001.wav"],
  "reward-xp": ["post game/earned XP/DSGNMisc_SKILL IMPACT-Glassy Sprites_HY_PC-001.wav"],
  "reward-ember": ["post game/earned ember/DSGNTonl_USABLE-Magic Coin_HY_PC-001.wav"],
  spend: ["ember/DSGNTonl_USABLE-Coin Spend_HY_PC-001.wav"],
};

// --- Music ----------------------------------------------------------------
const MUSIC = {
  home: [
    ["home-grace-at-dawnfall", "Home Screen/Grace at Dawnfall.mp3", "Grace at Dawnfall"],
    ["home-grace-at-dawnfall-2", "Home Screen/Grace at Dawnfall-2.mp3", "Grace at Dawnfall II"],
    ["home-of-grace", "Home Screen/Home of Grace.mp3", "Home of Grace"],
    ["home-of-grace-2", "Home Screen/Home of Grace-2.mp3", "Home of Grace II"],
  ],
  battle: [
    ["battle-everflame-hymn", "Battle/Everflame Battle Hymn.mp3", "Everflame Battle Hymn"],
    ["battle-everflame-hymn-2", "Battle/Everflame Battle Hymn-2.mp3", "Everflame Battle Hymn II"],
  ],
};

function assertExists(file, label) {
  if (!fs.existsSync(file)) {
    console.error(`✗ missing ${label}: ${file}`);
    process.exit(1);
  }
}

fs.mkdirSync(OUT_SFX, { recursive: true });
fs.mkdirSync(OUT_MUSIC, { recursive: true });

// --- convert SFX ---
const sfxManifest = {};
for (const [id, sources] of Object.entries(SFX)) {
  const files = [];
  sources.forEach((rel, i) => {
    const src = path.join(RAW, "Misc", rel);
    assertExists(src, id);
    const name = sources.length > 1 ? `${id}-${i + 1}.m4a` : `${id}.m4a`;
    const dst = path.join(OUT_SFX, name);
    // 64 kbps mono AAC — `--mix` downmixes stereo to one channel.
    execFileSync("afconvert", ["-f", "m4af", "-d", "aac", "-b", "64000", "--mix", src, dst]);
    files.push(`/audio/sfx/${name}`);
  });
  sfxManifest[id] = files;
}

// --- copy music ---
const musicManifest = { home: [], battle: [] };
for (const [group, entries] of Object.entries(MUSIC)) {
  for (const [id, rel, title] of entries) {
    const src = path.join(RAW, "Music", rel);
    assertExists(src, id);
    const name = `${id}.mp3`;
    fs.copyFileSync(src, path.join(OUT_MUSIC, name));
    musicManifest[group].push({ id, title, src: `/audio/music/${name}` });
  }
}

const generated = `// AUTO-GENERATED by scripts/stage-audio.mjs — do not edit by hand.
// SFX are 64 kbps mono AAC; music is the source MP3. Ids on the left are what
// the app plays (see src/lib/audio/).

export interface MusicTrack {
  id: string;
  title: string;
  src: string;
}

/** Effect id → one or more variants (the player picks at random). */
export const SFX_SOURCES: Record<string, string[]> = ${JSON.stringify(sfxManifest, null, 2)};

export type SfxId = keyof typeof SFX_SOURCES;

/** Everywhere outside a fight: home, explore, shop, settings, training. */
export const HOME_TRACKS: MusicTrack[] = ${JSON.stringify(musicManifest.home, null, 2)};

/** Matches, from the first round through the post-match beats. */
export const BATTLE_TRACKS: MusicTrack[] = ${JSON.stringify(musicManifest.battle, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, "src", "config", "audio.generated.ts"), generated);

const sfxBytes = fs
  .readdirSync(OUT_SFX)
  .reduce((n, f) => n + fs.statSync(path.join(OUT_SFX, f)).size, 0);
const musicBytes = fs
  .readdirSync(OUT_MUSIC)
  .reduce((n, f) => n + fs.statSync(path.join(OUT_MUSIC, f)).size, 0);
console.log(
  `Staged ${Object.keys(sfxManifest).length} effects (${(sfxBytes / 1024).toFixed(0)} KB) and ` +
    `${musicManifest.home.length + musicManifest.battle.length} tracks (${(musicBytes / 1048576).toFixed(1)} MB).`,
);
